### ISSUE TITLE
Send audio from client machine to server.

### ISSUE THREAD

**Issue by hajicj** [hajicj/HAMR_2016#5]
Currently, we rely on the server running on the same machine. We need to decouple this and send the audio file to the server properly.

**Comment by hajicj** [comment]
**Who calls Google's ASR API: client, or server?**

Calling the Google voice API from the client means sending credentials from the server to the client, which we decided is bad practice. So, the client sends the audio to the server.

**Comment by hajicj** [comment]
**Progress:**

Writing a post requirement to send the audio blob. @mbuccoli Can you record it more accurately here?

**Comment by mbuccoli** [comment]
Made the modification
